import 'uno.css'
import '@unocss/reset/tailwind.css'
import './styles/base.css'
import '@vue/devtools-ui/style.css'
import '@vue/devtools-ui/uno.css'

export * from './composables/custom-inspector'
export * from './modules/components'
export * from './modules/custom-inspector'
export * from './modules/pinia'
export * from './modules/router'
