import 'uno.css'
import '@unocss/reset/tailwind.css'
import './styles/base.css'
import 'floating-vue/dist/style.css'

export * from './modules/pinia'
export * from './modules/components'
export * from './modules/router'
export * from './modules/vue-query'
export * from './modules/vuex'
